# bridge_config.yaml

- gz_topic_name: "/world/baylands/clock"
  ros_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"

# Drone 1 bridges
- gz_topic_name: "/world/baylands/model/x500_depth_mono_0/link/camera_link/sensor/IMX214/image"
  ros_topic_name: "/drone1/rgb_camera"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  frame_id: "drone1/camera_link"

- gz_topic_name: "/world/baylands/model/x500_depth_mono_0/link/camera_link/sensor/IMX214/camera_info"
  ros_topic_name: "/drone1/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  frame_id: "drone1/camera_link"

- gz_topic_name: "/world/baylands/model/x500_depth_mono_0/link/camera_link/sensor/StereoOV7251/depth_image"
  ros_topic_name: "/drone1/depth_camera"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  frame_id: "drone1/camera_link"